exec-once=waypaper --restore
exec-once = waybar -c ~/.config/archrice/waybar/config -s ~/.config/archrice/waybar/style.css
exec-once = swww-daemon
exec-once = hypridle

$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
