
exec-once = swww-daemon
exec-once = hypridle
exec-once = ~/.config/archrice/scripts/autostart.sh
exec-once = ~/.config/archrice/scripts/wal-reload.sh

$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24