#Eu estou usando o waypaper para a seleção de wallpaper(front end) mas estou usando mpvpaper para o backend 
#Esse código deixa rodando o ultimo wallpaper selecionado no waypapaer 
wallpaper {
    monitor = ""
    path = /home/kayotest/.config/archrice/wallpapers/
    fit_mode = cover
}
